---
- name: ensure Shanghai time
  copy:
    src: Shanghai
    dest: /etc/localtime
    owner: root
    group: root
    mode: 0644
    
- name: install ntpdate
  package: name=ntpdate state=present
  notify: 
    - sync time

- name: sync time
  cron: name="sync time" minute="*/5" user="root" job="ntpdate {{ ntp_server }} >> /root/Systime"

