---
- name: create aliyun and epel repo for CentOS 6
  copy: src={{ item }} dest=/etc/yum.repos.d/{{ item }}
  with_items:
    - Centos-6.repo
    - epel-6.repo
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

- name: create aliyun and epel repo for CentOS 7
  copy: src={{ item }} dest=/etc/yum.repos.d/{{ item }}
  with_items:
    - Centos-7.repo
    - epel-7.repo
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: update repo sources.list for ubuntu 16.04
  copy:
    src: sources.list.16.04
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16"

  
- name: update repo sources.list for ubuntu 18.04
  copy:
    src: sources.list.18.04
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18"

- name: ensure /root/.pip directory
  file:
    path: /root/.pip
    state: directory

- name: update pip repo
  copy:
    src: pip.conf
    dest: /root/.pip/pip.conf
    owner: root
    group: root
    mode: 0644
