- name: install zabbix agent
  yum: name=zabbix22-agent state=installed

- name: create /etc/zabbix/zabbix_agentd.d
  file: path=/etc/zabbix/zabbix_agentd.d state=directory owner=root group=root mode=0755
- name: copy config file

  template: src=zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf
  notify:
    - start zabbix agent
