---
  sysctl: name=net.ipv4.ip_forward value=1 state=present
  
  sysctl: name=vm.swappiness value=1 state=present
  
  sysctl: name=net.ipv4.conf.all.rp_filter value=0 state=present
  
  sysctl: name=net.ipv4.neigh.default.gc_stale_time value=120 state=present
  
  sysctl: name=net.ipv4.conf.default.rp_filter value=0 state=present
  
  sysctl: name=net.ipv4.tcp_max_tw_buckets value=5000 state=present
  
  sysctl: name=net.ipv4.tcp_max_syn_backlog value=1048576 state=present
  
  sysctl: name=net.ipv4.tcp_fin_timeout value=30 state=present
  
  sysctl: name=net.ipv4.tcp_keepalive_time value=1200 state=present
  
  sysctl: name=net.ipv4.tcp_syncookies value=1 state=present
  
  sysctl: name=net.ipv4.tcp_tw_reuse value=1 state=present
  
  #sysctl: name=net.ipv4.tcp_tw_recycle value=1 state=present
  
  #sysctl: name=net.ipv4.tcp_timestamps value=0 state=present
  
  sysctl: name=net.ipv4.ip_local_port_range value="1024 65535" state=present
  
- sysctl: name=net.ipv4.tcp_syn_retries value=6 state=present
- sysctl: name=net.ipv4.tcp_synack_retries value=2 state=present


- sysctl: name=net.core.somaxconn value=1048576 state=present
- sysctl: name=net.core.netdev_max_backlog value=1048576 state=present

- sysctl: name=net.ipv4.route.gc_timeout value=100 state=present

#- name: set net.ipv4.conf.default.arp_announce to 2 in /etc/sysctl.conf
#  sysctl: name=net.ipv4.conf.default.arp_announce value=2 state=present
#- name: set net.ipv4.conf.all.arp_announce to 2 in /etc/sysctl.conf
#  sysctl: net.ipv4.conf.all.arp_announce value=2 state=present
#- name: set net.ipv4.conf.lo.arp_announce to 2 in /etc/sysctl.conf
#  sysctl: name=net.ipv4.conf.lo.arp_announce value=2 state=present
