---
- name: create aliyun and epel repo for CentOS 6
  copy: src={{ item }} dest=/etc/yum.repos.d/{{ item }}
  with_items:
    - Centos-6.repo
    - epel-6.repo
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

- name: create aliyun and epel repo for CentOS 7
  copy: src={{ item }} dest=/etc/yum.repos.d/{{ item }}
  with_items:
    - Centos-7.repo
    - epel-7.repo
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

#- name: install Development Tools
#  yum: name={{ item }} state=installed
#  tags:
#    - INSTALL
#  with_items:
#    - '@"Development Tools"'
#    - "vim"
