---
# handlers file for base2
#
- name: sync time
  shell: ntpdate {{ ntp_server }}

- name: start zabbix agent
  service: name=zabbix-agent state=restarted enabled=yes

- name: restart snmp
  service: name=snmpd state=restarted  enabled=yes


- name: restart systemd-resolved
  service:
    name: systemd-resolved
    state: restarted
