- name: cp kube-scheduler bin file to /opt/kubernetes/bin
  copy:
    src: kube-scheduler
    dest: /opt/kubernetes/bin/kube-scheduler
    owner: root
    group: root
    mode: 0755

- name: cp kube-scheduler.service to /lib/systemd/system
  template:
    src: kube-scheduler/kube-scheduler.service.j2
    dest: /lib/systemd/system/kube-scheduler.service
    owner: root
    group: root
    mode: 0644
  notify: restart kube-scheduler

#- name: daemon reload
#  command: systemctl daemon-reload

- name:  start kube-scheduler
  service:
    name: kube-scheduler
    state: started
    enabled: yes
    daemon_reload: yes
