- hosts: k8s-etcd
  roles:
    - /etc/ansible/roles/kubernetes/etcd

- hosts: k8s-master
  roles:
#    - /etc/ansible/roles/kubernetes/docker
    - /etc/ansible/roles/kubernetes/k8s-common
    - /etc/ansible/roles/kubernetes/k8s-master

- hosts: k8s-node
  roles:
#    - /etc/ansible/roles/kubernetes/docker
    - /etc/ansible/roles/kubernetes/flannel
    - /etc/ansible/roles/kubernetes/k8s-common
    - /etc/ansible/roles/kubernetes/k8s-node
